# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 57020b455928446f408e7883ae29f7046465973b

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/1/
Content-Type: application/json
Authorization: Token 57020b455928446f408e7883ae29f7046465973b

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2026-09-01
Content-Type: application/json

###

POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Второе объявление",
    "description": "Проверяем удаление",
    "status": "OPEN"
}

###

DELETE {{baseUrl}}/advertisements/2/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b


###
#Удаление комментария другого пользователя 
DELETE {{baseUrl}}/advertisements/1/
Authorization: Token 324e62b621ac4e29797f18c193a3b84e40a50d54

###

PATCH {{baseUrl}}/advertisements/1/
Authorization: Token 324e62b621ac4e29797f18c193a3b84e40a50d54
Content-Type: application/json

{
    "title": "Я пытаюсь изменить чужое объявление"
}



###
# Проверка лимита на объявления 

POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 2",
    "description": "Проверка лимита",
    "status": "OPEN"
}



###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 3",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 4",
    "description": "Проверка лимита",
    "status": "OPEN"
}


###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 5",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 6",
    "description": "Проверка лимита",
    "status": "OPEN"
}


###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 7",
    "description": "Проверка лимита",
    "status": "OPEN"
}


###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 8",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 9",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 10",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 11",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
POST {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b
Content-Type: application/json

{
    "title": "Объявление 12",
    "description": "Проверка лимита",
    "status": "OPEN"
}

###
GET {{baseUrl}}/advertisements/

###
GET {{baseUrl}}/advertisements/

###
GET {{baseUrl}}/advertisements/
Authorization: Token 57020b455928446f408e7883ae29f7046465973b